### ISSUE TITLE
[Bug]: Sidebar transparency issue

### ISSUE THREAD

**Issue by radualexe32** [illixion/vscode-vibrancy-continued#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The screen shot below show show the code sidebar transparency is not exactly the same as the rest of code ide,

![CleanShot 2024-02-03 at 19 38 48](https://github.com/illixion/vscode-vibrancy-continued/assets/95101627/8bcae3c6-3f46-40b1-9679-3fa604f50f36)

### Expected Behavior

From the screenshots it seems as though the sidebar transparency and in general the rest of the code ide should all be uniform and look the same.

### Environment

```markdown
- OS: 14.3
- VSCode: 1.86.0
- Extension: 1.1.27
- Theme: Dark+
```

**Comment by illixion** [comment]
I think that's intentional just so there's some level of separation between different elements, if this is undesired then you can try using the [custom import](https://github.com/illixion/vscode-vibrancy-continued#vscode_vibrancyimports) feature with a [modified theme](https://github.com/illixion/vscode-vibrancy-continued/tree/master/themes).
