### ISSUE TITLE
[Bug]: Terminal doesn't retain vibrancy effect when dragged into the "main section"

### ISSUE THREAD

**Issue by tthn0** [illixion/vscode-vibrancy-continued#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I drag the integrated terminal into the "main section" (not sure what it's called), it turns opaque.

### Expected Behavior

Terminal should still retain vibrancy effect when dragged into the "main section."

### Steps To Reproduce

Just drag terminal into "main section." Video: https://imgur.com/rxg7bZR.

### Environment

```markdown
- OS: macOS Ventura macOS 13.3
- VSCode: Version: 1.77.3
- Extension: 1.1.14
```

**Comment by illixion** [comment]
Just checked and I'm not seeing this issue on my end. Have you tried the solution mentioned in the [FAQ](https://github.com/illixion/vscode-vibrancy-continued#effect-doesnt-work-for-terminal)?

> ## Effect doesn't work for terminal?
> Check your settings. You should change the renderer type of the terminal to dom.
>
> `"terminal.integrated.gpuAcceleration": "off"`

**Comment by tthn0** [comment]
I currently have `"terminal.integrated.gpuAcceleration": "off"`, and it's working fine when the terminal is in its "default position. However, when I drag it into the "main section" of VS Code, it no longer has the vibrancy effect.

**Comment by illixion** [comment]
I understand what the issue is that you're experiencing, but I can't replicate it on my machine.

https://user-images.githubusercontent.com/14954655/236621226-afe00a56-418e-4906-b26a-889e3ec4dfe8.mov

I also just noticed that you don't seem to have a sidebar, perhaps you have some other customizations or extensions that change how the full-screen terminal window works?

**Comment by tthn0** [comment]
I prefer to have the status bar, activity bar, and side bar hidden. I re-enabled all of those and tried dragging the terminal into the main section, but I'm still having the issue. I also looked through all of my other extensions, and I'm pretty sure none of them change how the full-screen terminal window works.

**Comment by illixion** [comment]
Hmm, could you try using extension bisect? Would be good to to confirm that this isn't caused by other extensions. You could also try checking if all of your "Window" settings in VSCode are set to defaults, as I've seen some of those settings cause issues if changed.

![Screenshot 2023-05-07 at 14 25 32](https://user-images.githubusercontent.com/14954655/236674660-5613ec86-84d0-4167-80c4-87be74db9ab4.png)

**Comment by illixion** [comment]
Also, what theme are you currently using? I haven't checked all of the alternative themes, so it's possible that one of them might be missing the terminal background customization. Dark+ is the one I'm using.

**Comment by tthn0** [comment]
Sorry for the late response. I just tried using one of the default VS Code themes, and the issue no longer occurs. It seems like my current theme ([Ninja UI Vibrant](https://marketplace.visualstudio.com/items?itemName=ntkvu.ninja-ui-vibrant)) conflicts with Vibrancy.

**Comment by illixion** [comment]
Yeah, using an incompatible theme would definitely cause something like this. Vibrancy requires a [compatible theme](https://github.com/illixion/vscode-vibrancy-continued#vscode_vibrancytheme) to be used, so you'll have to either switch to a compatible theme or create your own that would work with Ninja UI Vibrant. If you decide to go with latter, feel free to make a PR and I'll include your theme in Vibrancy so others can also use it.
