### ISSUE TITLE
[Feature]: Auto theme

### ISSUE THREAD

**Issue by RoyalFoxy** [illixion/vscode-vibrancy-continued#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Im frustrated when I use my own theme that isn't supported by vibrancy-continued

### Describe your idea or feature request

I would like, if possible, to have vibrancy automatically detect the theme and the different colors.

### Describe alternatives you've considered

Maybe have a system where the user can easily customize each color or just in general customize vibrancy.

**Comment by illixion** [comment]
The technical reason for why a theme has to be "supported" is because some themes use different CSS selectors and add their own elements, meaning that Vibrancy's transparency might be obscured by other elements or not work at all. Customization would really only be possible for existing themes, since expecting end users to locate CSS selectors is unrealistic.  Feature request for customizing existing themes is tracked under #83.
